/*
This file contains all constants in the app.
*/

module.exports = {
	// ACTION TYPES
	AIM_AT: "AIM_AT",
	KILL_HERO: "KILL_HERO",
	RESET: "RESET",
	DUCK_DOWN: "DUCK_DOWN",
	STAND_UP: "STAND_UP",

	// HERO STATUSES
	AIMING: "AIMING",
	DUCKING: "DUCKING",
	WAITING: "WAITING",
	DEAD: "DEAD",

	GET_MEMBERS:'GET_MEMBERS',
	REMOVE_MEMBER:'REMOVE_MEMBER',
	ADD_MEMBER: 'ADD_MEMBER',
	INIT_MEMBERS_LIST: 'INIT_MEMBERS_LIST'
};